### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by byronbytes** [betterclient/lunarclient-sodium-hacks#3]
I tried putting this into the overrides folder in Lunar and it didn't work. I also tried to run it and it gave me these errors.
![image](https://user-images.githubusercontent.com/53088136/230526494-58b288ce-a158-46f7-bb24-983cf4f0a609.png)
![image](https://user-images.githubusercontent.com/53088136/230526499-131946f5-548b-4c07-9c67-7317a6f8be9b.png)

**Comment by betterclient** [comment]
you don't put it into the overrides folder, can you run the jar file using the terminal?

**Comment by byronbytes** [comment]
> you don't put it into the overrides folder, can you run the jar file using the terminal?

If you meant terminal as in CMD, no, it still does not work.
![image](https://user-images.githubusercontent.com/53088136/230801362-73730177-238a-4c2b-91c8-bd80c8d74759.png)

**Comment by betterclient** [comment]
you do java -jar sodium-util.jar, also use new version lunar updated the sodium files
