### ISSUE TITLE
How do I use it

### ISSUE THREAD

**Issue by fgvviu923yu487asc** [betterclient/lunarclient-sodium-hacks#4]
It overrided but like, is there a keybind for the hack, or like does it do somethign without showing how can I use the hacks it self?

**Comment by Pythoral** [comment]
press F9

**Comment by byronbytes** [comment]
How did you get it to work?

**Comment by betterclient** [comment]
ok

**Comment by Fire12Sam** [comment]
@betterclient Yo it says java error encored when i launch it

**Comment by betterclient** [comment]
show the error
